[workspace]
members = [
    "crates/lib/*",
    "crates/lib/graph/examples/*",

    "crates/editor",
]
default-members = ["crates/editor", "crates/lib/*"]
exclude = ["crates/lib/asset-runtime"]

resolver = "2"


[profile.release.build-override]
opt-level = 3
codegen-units = 16
[profile.dev.build-override]
opt-level = 3
