[workspace]
members = [
    "crates/lib/*",
    "crates/lib/graph/examples/*",

    "crates/editor",
]
default-members = ["crates/editor", "crates/lib/*"]

resolver = "2"

[profile.release.build-override]
opt-level = 3
codegen-units = 24
[profile.dev.build-override]
opt-level = 3

[workspace.dependencies]
ash = "0.37.3"
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
bytemuck = { version = "1.15.0", features = ["derive"] }
cargo_toml = { version = "0.19.2" }
crossbeam-channel = "0.5.12"
dashmap = "5.5.3"
egui = { version = "0.24.0", features = ["bytemuck"] }
egui_extras = "0.24.0"
egui_grid = "0.4.0"
egui-winit = "0.24.0"
gltf = { version = "1.4.0" }
gpu-allocator = { version = "0.25.0", features = ["vulkan", "visualizer"] }
hassle-rs = { version = "0.11.0" }
hashbrown = { version = "0.14.3", features = ["nightly"] }
meshopt = { git = "https://github.com/gwihlidal/meshopt-rs" }
parking_lot = { version = "0.12.1", features = ["hardware-lock-elision"] }
quote = "1.0.35"
rand = "0.8.5"
range-alloc = "0.1.3"
raw-window-handle = "0.5.0"
rayon = "1.9.0"
rfd = "0.12.1"
rustc-hash = "1.1.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.114" }
static_assertions = "1.1.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracy = { package = "tracy_full", version = "1.7.1", features = ["enable", "tracing"] }
uuid = { version = "1.7.0", features = ["v4", "fast-rng", "serde"] }
vek = { version = "0.16.1", features = ["bytemuck", "serde"] }
walkdir = "2.5.0"
winit = "0.28"
zstd = "0.13.0"

