[package]
name = "radiance-render"
version = "0.1.0"
edition = "2021"

[build-dependencies]
radiance-shader-compiler = { path = "../shader-compiler", features = ["build-script"] }

[dependencies]
radiance-shader-compiler = { path = "../shader-compiler", features = ["runtime"] }
