[package]
name = "rad-window"
version = "0.1.0"
edition = "2021"

[dependencies]
rad-core = { workspace = true }
rad-graph = { workspace = true }

tracing = { workspace = true }
winit = { workspace = true }
