[package]
name = "rad-window"
version = "0.1.0"
edition = "2021"

[dependencies]
rad-core = { path = "../rad-core" }
rad-graph = { path = "../rad-graph" }

tracing = { workspace = true }
winit = { workspace = true }
