[package]
name = "radiance-passes"
version = "0.0.0"
edition = "2021"

[dependencies]
radiance-asset = { path = "../asset" }
radiance-graph = { path = "../graph", features = ["bytemuck"] }

ash = { workspace = true }
bytemuck = { workspace = true }
vek = { workspace = true }

